# Generated by Django 2.2.1 on 2019-05-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageanalyzeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='ImageMetaDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=20, max_digits=21)),
                ('height', models.DecimalField(decimal_places=20, max_digits=21)),
                ('left', models.DecimalField(decimal_places=20, max_digits=21)),
                ('top', models.DecimalField(decimal_places=20, max_digits=21)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageanalyzeapp.ImageModel')),
            ],
        ),
    ]
