# Generated by Django 2.2.1 on 2019-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageanalyzeapp', '0002_auto_20190504_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadatamodel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imagemetadatamodel',
            name='left',
        ),
        migrations.RemoveField(
            model_name='imagemetadatamodel',
            name='top',
        ),
        migrations.RemoveField(
            model_name='imagemetadatamodel',
            name='width',
        ),
        migrations.AddField(
            model_name='imagemetadatamodel',
            name='x1',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imagemetadatamodel',
            name='x2',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imagemetadatamodel',
            name='y1',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imagemetadatamodel',
            name='y2',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
